### ISSUE TITLE
Ubuntu install

### ISSUE THREAD

**Issue by colindaven** [mortonjt/SCOPE#1]
The Ubuntu 14.04 installation is a little tricky since I cannot locate the autotools packages (merely autotools-dev and ui-auto.
http://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=ui-auto&searchon=names

The program appears to compile fine, but on running throws this error:

"terminate called after throwing an instance of 'std::system_error'
  what():  Enable multithreading to use std::thread: Operation not permitted
"

I have tried adding -lpthread to the makefiles, but have not got any further. Suggestions ?

**Comment by mortonjt** [comment]
I just tested the installation on a fresh install of Ubuntu 14.04.  I'm convinced that the installer was having problems finding the pthread libraries.

An updated configure.ac file is now on the repository.  It works for my Ubuntu 14.04 install.

Thank you very much for raising this issue. 
Let me know if this fix works for you.

Best,
Jamie

**Comment by colindaven** [comment]
Thanks, I recompiled with the changed configure.ac file and it now appears to be working fine. 

Best Regards,
Colin
